In [ ]:
!pip install -q tensorflow-recommenders

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '-1'
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

In [3]:
from typing import Dict, Text
import numpy as np
import pandas as pd
import tensorflow as tf

import tensorflow_recommenders as tfrs

In [4]:
# Read in data from pickle
import pickle
import pandas as pd
df = pd.DataFrame();
#with (open('model_data.pickle','rb')) as openfile:
    #df = pickle.load(openfile)
#df.head()

In [55]:
#data_set = pd.read_csv('model_data.csv')
data_set.head()

C:\Users\RSanchez\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (18) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


MemoryError: Unable to allocate 1.74 GiB for an array with shape (27, 8635403) and data type object

In [50]:
train_set = tf.data.TextLineDataset('model_data.csv')
COLUMNS = [
    'business_id',
    'business_stars',
    'review_count',
    'categories',
    'user_id',
    'text',
    'review_stars',
    'restaurants_table_service',
    'wifi',
    'bike_parking',
    'business_parking',
    'business_accepts_credit_cards',
    'restaurants_reservations',
    'wheelchair_accessible',
    'caters',
    'outdoor_seating',
    'restaurants_good_for_groups',
    'happy_hour',
    'business_accepts_bitcoin',
    'restaurants_price_range2',
    'ambience',
    'has_tv',
    'alcohol',
    'good_for_meal',
    'dogs_allowed',
    'restaurants_take_out',
    'noise_level',
    'restaurants_attire',
    'restaurants_delivery',
    'good_for_kids',
    'good_for_dancing',
    'music'
]
DEFAULTS = [[0],]


In [51]:
def _parse_line(line):
    # Decode the line into its fields
    fields = tf.io.decode_csv(line, DEFAULTS)

    # Pack the result into a dictionary
    features = dict(zip(COLUMNS,fields))

    # Separate the label from the features
    label = features.pop('business_id')

    return features, label

trainset = train_set.map(_parse_line)
print(trainset)

<MapDataset shapes: ({business_stars: (), review_count: (), categories: (), user_id: (), text: (), review_stars: (), restaurants_table_service: (), wifi: (), bike_parking: (), business_parking: (), business_accepts_credit_cards: (), restaurants_reservations: (), wheelchair_accessible: (), caters: (), outdoor_seating: (), restaurants_good_for_groups: (), happy_hour: (), business_accepts_bitcoin: (), restaurants_price_range2: (), ambience: (), has_tv: (), alcohol: (), good_for_meal: (), dogs_allowed: (), restaurants_take_out: (), noise_level: (), restaurants_attire: (), restaurants_delivery: (), good_for_kids: (), good_for_dancing: (), music: ()}, ()), types: ({business_stars: tf.float32, review_count: tf.float32, categories: tf.float32, user_id: tf.float32, text: tf.float32, review_stars: tf.float32, restaurants_table_service: tf.float32, wifi: tf.float32, bike_parking: tf.float32, business_parking: tf.float32, business_accepts_credit_cards: tf.float32, restaurants_reservations: tf.floa

In [ ]:
x = tf.compat.v1.data.make_one_shot_iterator(trainset)
x.next()

In [19]:
california_housing_dataframe = pd.read_csv("model_data_min2.csv")
# Define the input feature: total_rooms
features = california_housing_dataframe["user_id"]

# Define the label
targets = california_housing_dataframe["business_id"]
# Convert pandas data into a dict of np arrays.
features = {key:np.array(value) for key,value in dict(features).items()}                                           

display(features)

{0: array('93z0yh-sUpGZS-cSKu6xxA', dtype='<U22'),
 1: array('Q_CZIvnsDHjpls-EPzzG7Q', dtype='<U22'),
 2: array('rqxTSFFj5fZNmabY1fmTlw', dtype='<U22'),
 3: array('vNPxlt5f50q0e2nVAScW3Q', dtype='<U22'),
 4: array('eXRC79iX60xwA1UuGRuWNg', dtype='<U22'),
 5: array('KWfCQBcKrCaXn4tekg_xzA', dtype='<U22'),
 6: array('W4BsqdIQUGCogRBE_Hf8OQ', dtype='<U22'),
 7: array('scorlJp8YMJdBUcLGcMuaw', dtype='<U22'),
 8: array('Y3e5gyyiWlo0I47A9aIMfw', dtype='<U22'),
 9: array('-qiFxzpUBOnZ28l_KMgTXw', dtype='<U22'),
 10: array('XHmpu1NsPx06bqnJ61HX2g', dtype='<U22'),
 11: array('Ys_Z4SBt9z0W2SBToyVzIQ', dtype='<U22'),
 12: array('wP3lu1-_irXB7OqXTX-awg', dtype='<U22'),
 13: array('-B9h9P456KrNogBrwv7vXQ', dtype='<U22'),
 14: array('TU1n0vy2S8v_ATn3Ux6pvg', dtype='<U22'),
 15: array('8PVEmbVNL1v2ccL3eoGY5g', dtype='<U22'),
 16: array('G-hkH1pn3hnua1xV4LEr0Q', dtype='<U22'),
 17: array('f1eUhIzluYveIZtSalya5Q', dtype='<U22'),
 18: array('46j1gVNFNB274n9Abrn_7Q', dtype='<U22'),
 19: array('lKskBmmuBG

In [21]:
# Construct a dataset, and configure batching/repeating.
#ds = tf.data.Dataset.from_tensor_slices((features,targets))
# Construct a dataset, and configure batching/repeating.
ds = tf.data.Dataset.from_tensor_slices((california_housing_dataframe['user_id'],california_housing_dataframe['business_id']))

In [22]:
for x in ds.take(2):
    print(x)

(<tf.Tensor: shape=(), dtype=string, numpy=b'93z0yh-sUpGZS-cSKu6xxA'>, <tf.Tensor: shape=(), dtype=string, numpy=b'6iYb2HFDywm3zjuRg0shjw'>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Q_CZIvnsDHjpls-EPzzG7Q'>, <tf.Tensor: shape=(), dtype=string, numpy=b'6iYb2HFDywm3zjuRg0shjw'>)


In [24]:
california_housing_dataframe = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")
# Define the input feature: total_rooms
my_feature = california_housing_dataframe[["total_rooms"]]

# Configure a numeric feature column for total_rooms
feature_columns = [tf.feature_column.numeric_column("total_rooms")]

# Define the label
targets = california_housing_dataframe["median_house_value"]

# Convert pandas data into a dict of np arrays.
features = {key:np.array(value) for key,value in dict(features).items()}                                           

# Construct a dataset, and configure batching/repeating.
ds = tf.data.Dataset.from_tensor_slices((features,targets))

ValueError: Value tf.Tensor(b'93z0yh-sUpGZS-cSKu6xxA', shape=(), dtype=string) has insufficient rank for batching.

In [23]:
type(ds)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [ ]:
# Filter out data
user_reviews = df[['user_id','business_id']]
businesses = df['business_id']
businesses.drop_duplicates(inplace=True)
businesses.head()

In [ ]:
user_reviews.head()

In [ ]:
user_ids2 = tf.data.Dataset.from_tensor_slices(user_reviews['user_id'])
businesses = tf.data.Dataset.from_tensor_slices(businesses)


In [ ]:
user_reviews_formated = [] 
for index, row in user_reviews.iloc[0:100000].iterrows():
    user_reviews_formated.append({"business_id": tf.constant(row['business_id']),"user_id": tf.constant(row['user_id'])})
user_reviews_formated[0]

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(user_reviews)
for x in dataset.take(1):
    print(x)

~~###### Credit: Raul if this works~~

In [ ]:
user_ids_vocab = tf.keras.layers.experimental.preprocessing.StringLookup(mask_token=None)
user_ids_vocab.adapt(user_ids2)

In [ ]:
business_id_vocab = tf.keras.layers.experimental.preprocessing.StringLookup(mask_token=None)
business_id_vocab.adapt(businesses)

In [ ]:
class business_rec_model(tfrs.Model):

  def __init__(
      self,
      user_model: tf.keras.Model,
      business_model: tf.keras.Model,
      task: tfrs.tasks.Retrieval):
    super().__init__()

    self.user_model = user_model
    self.business_model = business_model

    self.task = task

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    user_embeddings = self.user_model(features["user_id"])
    business_embeddings = self.business_model(features["business_id"])

    return self.task(user_embeddings, business_embeddings)

In [ ]:
user_model = tf.keras.Sequential([
    user_ids_vocab,
    tf.keras.layers.Embedding(user_ids_vocab.vocabulary_size(),64)
])
business_model = tf.keras.Sequential([
    business_id_vocab,
    tf.keras.layers.Embedding(business_id_vocab.vocabulary_size(),64)
])

task = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(
    businesses.batch(128).map(business_model)
))

In [ ]:
model = business_rec_model(user_model,business_model,task)
model.compile(optimizer = tf.keras.optimizers.Adagrad(.5))

In [ ]:
for x in range(0,10):
    print(user_reviews_formated[x])

In [ ]:
for x in businesses.take(10):
    print(x)

In [ ]:
model.fit(dataset,batch_size=1000,epochs=3, use_multiprocessing=True)